//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beadando__Z86RKF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realestate
    {
        public string LOCATION { get; set; }
        public int SQUAREM { get; set; }
        public string COLOR { get; set; }
        public string DIRECTION { get; set; }
        public int LEVELS { get; set; }
        public bool POOL { get; set; }
        public string EMAIL { get; set; }
    }
}
